# Generated by Django 5.2.6 on 2025-09-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('kategoriya', models.CharField(choices=[('ish_haqi', 'Ish haqi'), ('biznes', 'Biznes'), ("sovg'a", 'Sovg‘a'), ('boshqa', 'Boshqa')], max_length=50)),
                ('tolov_usuli', models.CharField(choices=[('naqd', 'Naqd'), ('bank', 'Bank'), ('karta', 'Karta')], max_length=50)),
                ('izoh', models.TextField(blank=True, null=True)),
                ('sana', models.DateField()),
                ('vaqt', models.TimeField(blank=True, null=True)),
                ('takroriymi', models.BooleanField(default=False)),
                ('eslatma', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Xarajat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('kategoriya', models.CharField(choices=[('biznes', 'Biznes'), ('shaxsiy', 'Shaxsiy'), ('transport', 'Transport'), ('ovqat', 'Ovqat')], max_length=50)),
                ('tolov_usuli', models.CharField(choices=[('naqd', 'Naqd'), ('bank', 'Bank'), ('karta', 'Karta')], max_length=50)),
                ('izoh', models.TextField(blank=True, null=True)),
                ('sana', models.DateField()),
                ('vaqt', models.TimeField(blank=True, null=True)),
                ('takroriymi', models.BooleanField(default=False)),
                ('eslatma', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
